# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

use_frameworks! :linkage => :static


target 'FoodHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodHelper
	pod 'Firebase/Analytics'     # analytics
pod 'Firebase/Auth'          # authentication
pod 'Firebase/Firestore'     # Firestore database
pod 'Firebase/Database'      # Realtime Database
pod 'Firebase/Storage' 

end
